-- MySQL Script generated by MySQL Workbench
-- 11/30/16 14:20:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bibliotheque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotheque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotheque` DEFAULT CHARACTER SET utf8mb4 ;
USE `bibliotheque` ;

-- -----------------------------------------------------
-- Table `bibliotheque`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`languages` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`genres` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`locations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `bibliotheque`.`editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`editors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `website` VARCHAR(255) NULL,
  `logo` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`books` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `front_cover` VARCHAR(255) NULL,
  `summary` TEXT NULL,
  `isbn` VARCHAR(255) NULL,
  `npage` INT(10) NULL,
  `datepub` DATE NULL,
  `language_id` INT(10) UNSIGNED NULL,
  `genre_id` INT(10) UNSIGNED NULL,
  `location_id` INT(10) UNSIGNED NULL,
  `editor_id` INT(10) UNSIGNED NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `books_isbn_unique` (`isbn` ASC),
  INDEX `books_languages_id_foreign` (`language_id` ASC),
  INDEX `books_genre_id_foreign` (`genre_id` ASC),
  INDEX `books_location_id_foreign` (`location_id` ASC),
  INDEX `books_editor_id_foreign` (`editor_id` ASC),
  CONSTRAINT `books_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `bibliotheque`.`languages` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `books_genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `bibliotheque`.`genres` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `books_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `bibliotheque`.`locations` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `books_edithor_id`
    FOREIGN KEY (`editor_id`)
    REFERENCES `bibliotheque`.`editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `datebirth` DATE NULL,
  `datedeath` DATE NULL,
  `bio` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`author_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`author_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT(10) ZEROFILL NULL,
  `book_id` INT(10) ZEROFILL NULL,
  PRIMARY KEY (`id`),
  INDEX `author_book_author_id` (`author_id` ASC),
  INDEX `author_book_book_id` (`book_id` ASC),
  CONSTRAINT `author_book_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `bibliotheque`.`authors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `author_book_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `bibliotheque`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`account_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `account_type_id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(255) NULL,
  `confirmed_email` TINYINT(1) NULL,
  `city` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `users_account_type_id` (`account_type_id` ASC),
  CONSTRAINT `users_account_type_id`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `bibliotheque`.`account_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`book_instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`book_instances` (
  `id` VARCHAR(36) NOT NULL COMMENT 'lors de l\'insert, utiliser UUID() pour l\'ID',
  `book_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `book_instances_book_id` (`book_id` ASC),
  CONSTRAINT `book_instances_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `bibliotheque`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`borrowing_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`borrowing_history` (
  `book_instances_id` VARCHAR(36) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `borrowed_since` TIMESTAMP NOT NULL,
  `borrowed_to` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  INDEX `borrowing_history_user_id` (`user_id` ASC),
  INDEX `borrowing_history_book_instances_id` (`book_instances_id` ASC),
  CONSTRAINT `borrowing_history_book_instances_id`
    FOREIGN KEY (`book_instances_id`)
    REFERENCES `bibliotheque`.`book_instances` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `borrowing_history_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bibliotheque`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque`.`book_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`book_rating` (
  `book_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `comment` TEXT NULL,
  UNIQUE INDEX `book_rating_book_id_user_id` (`book_id` ASC, `user_id` ASC),
  INDEX `book_rating_user_id` (`user_id` ASC),
  INDEX `book_rating_book_id` (`book_id` ASC),
  CONSTRAINT `book_rating_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bibliotheque`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_rating_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `bibliotheque`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
